"""7

Revision ID: 0405816db021
Revises: a6026a9693d8
Create Date: 2022-03-28 16:31:38.237679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0405816db021'
down_revision = 'a6026a9693d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
