"""5

Revision ID: 0f713749d249
Revises: bc015570471e
Create Date: 2022-04-29 23:13:46.959659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f713749d249'
down_revision = 'bc015570471e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_requisition_items', 'line_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_requisition_items', sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
