"""3

Revision ID: 151013ade2b3
Revises: cfda656a1c11
Create Date: 2022-06-16 12:51:21.128393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151013ade2b3'
down_revision = 'cfda656a1c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_type', sa.Column('metadata_name', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'document_type', ['metadata_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_type', type_='unique')
    op.drop_column('document_type', 'metadata_name')
    # ### end Alembic commands ###
