"""1

Revision ID: 161bde616f12
Revises: 
Create Date: 2022-05-27 00:54:54.951629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161bde616f12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('approval_process_approval_template_id_fkey', 'approval_process', type_='foreignkey')
    op.drop_constraint('approval_process_entity_iin_fkey', 'approval_process', type_='foreignkey')
    op.drop_constraint('approval_process_document_type_id_fkey', 'approval_process', type_='foreignkey')
    op.drop_constraint('approval_process_status_fkey', 'approval_process', type_='foreignkey')
    op.create_foreign_key(None, 'approval_process', 'process_status_type', ['status'], ['name'])
    op.create_foreign_key(None, 'approval_process', 'entity', ['entity_iin'], ['iin'])
    op.create_foreign_key(None, 'approval_process', 'document_type', ['document_type_id'], ['id'])
    op.create_foreign_key(None, 'approval_process', 'approval_template', ['approval_template_id'], ['id'])
    op.drop_constraint('approval_route_employee_id_fkey', 'approval_route', type_='foreignkey')
    op.drop_constraint('approval_route_document_type_id_fkey', 'approval_route', type_='foreignkey')
    op.drop_constraint('approval_route_approval_process_id_fkey', 'approval_route', type_='foreignkey')
    op.drop_constraint('approval_route_type_fkey', 'approval_route', type_='foreignkey')
    op.drop_constraint('approval_route_entity_iin_fkey', 'approval_route', type_='foreignkey')
    op.drop_constraint('approval_route_approval_template_id_fkey', 'approval_route', type_='foreignkey')
    op.create_foreign_key(None, 'approval_route', 'document_type', ['document_type_id'], ['id'])
    op.create_foreign_key(None, 'approval_route', 'step_type', ['type'], ['name'])
    op.create_foreign_key(None, 'approval_route', 'approval_template', ['approval_template_id'], ['id'])
    op.create_foreign_key(None, 'approval_route', 'entity', ['entity_iin'], ['iin'])
    op.create_foreign_key(None, 'approval_route', 'employee', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'approval_route', 'approval_process', ['approval_process_id'], ['id'])
    op.drop_constraint('approval_status_status_fkey', 'approval_status', type_='foreignkey')
    op.drop_constraint('approval_status_document_type_id_fkey', 'approval_status', type_='foreignkey')
    op.drop_constraint('approval_status_entity_iin_fkey', 'approval_status', type_='foreignkey')
    op.drop_constraint('approval_status_approval_route_id_fkey', 'approval_status', type_='foreignkey')
    op.drop_constraint('approval_status_employee_id_fkey', 'approval_status', type_='foreignkey')
    op.create_foreign_key(None, 'approval_status', 'document_type', ['document_type_id'], ['id'])
    op.create_foreign_key(None, 'approval_status', 'employee', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'approval_status', 'entity', ['entity_iin'], ['iin'])
    op.create_foreign_key(None, 'approval_status', 'route_status_type', ['status'], ['name'])
    op.create_foreign_key(None, 'approval_status', 'approval_route', ['approval_route_id'], ['id'])
    op.drop_constraint('approval_template_document_type_id_fkey', 'approval_template', type_='foreignkey')
    op.drop_constraint('approval_template_entity_iin_fkey', 'approval_template', type_='foreignkey')
    op.create_foreign_key(None, 'approval_template', 'entity', ['entity_iin'], ['iin'])
    op.create_foreign_key(None, 'approval_template', 'document_type', ['document_type_id'], ['id'])
    op.drop_constraint('approval_template_step_type_fkey', 'approval_template_step', type_='foreignkey')
    op.drop_constraint('approval_template_step_employee_id_fkey', 'approval_template_step', type_='foreignkey')
    op.drop_constraint('approval_template_step_approval_template_id_fkey', 'approval_template_step', type_='foreignkey')
    op.create_foreign_key(None, 'approval_template_step', 'step_type', ['type'], ['name'])
    op.create_foreign_key(None, 'approval_template_step', 'employee', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'approval_template_step', 'approval_template', ['approval_template_id'], ['id'])
    op.drop_constraint('employee_entity_iin_fkey', 'employee', type_='foreignkey')
    op.drop_constraint('employee_user_id_fkey', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'employee', 'entity', ['entity_iin'], ['iin'])
    op.drop_constraint('purchase_requisition_counterparty_iin_fkey', 'purchase_requisition', type_='foreignkey')
    op.drop_constraint('purchase_requisition_entity_iin_fkey', 'purchase_requisition', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_requisition', 'entity', ['entity_iin'], ['iin'])
    op.create_foreign_key(None, 'purchase_requisition', 'counterparty', ['counterparty_iin'], ['iin'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_requisition', type_='foreignkey')
    op.drop_constraint(None, 'purchase_requisition', type_='foreignkey')
    op.create_foreign_key('purchase_requisition_entity_iin_fkey', 'purchase_requisition', 'entity', ['entity_iin'], ['iin'], ondelete='CASCADE')
    op.create_foreign_key('purchase_requisition_counterparty_iin_fkey', 'purchase_requisition', 'counterparty', ['counterparty_iin'], ['iin'], ondelete='CASCADE')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_user_id_fkey', 'employee', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('employee_entity_iin_fkey', 'employee', 'entity', ['entity_iin'], ['iin'], ondelete='CASCADE')
    op.drop_constraint(None, 'approval_template_step', type_='foreignkey')
    op.drop_constraint(None, 'approval_template_step', type_='foreignkey')
    op.drop_constraint(None, 'approval_template_step', type_='foreignkey')
    op.create_foreign_key('approval_template_step_approval_template_id_fkey', 'approval_template_step', 'approval_template', ['approval_template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('approval_template_step_employee_id_fkey', 'approval_template_step', 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('approval_template_step_type_fkey', 'approval_template_step', 'step_type', ['type'], ['name'], ondelete='CASCADE')
    op.drop_constraint(None, 'approval_template', type_='foreignkey')
    op.drop_constraint(None, 'approval_template', type_='foreignkey')
    op.create_foreign_key('approval_template_entity_iin_fkey', 'approval_template', 'entity', ['entity_iin'], ['iin'], ondelete='CASCADE')
    op.create_foreign_key('approval_template_document_type_id_fkey', 'approval_template', 'document_type', ['document_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'approval_status', type_='foreignkey')
    op.drop_constraint(None, 'approval_status', type_='foreignkey')
    op.drop_constraint(None, 'approval_status', type_='foreignkey')
    op.drop_constraint(None, 'approval_status', type_='foreignkey')
    op.drop_constraint(None, 'approval_status', type_='foreignkey')
    op.create_foreign_key('approval_status_employee_id_fkey', 'approval_status', 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('approval_status_approval_route_id_fkey', 'approval_status', 'approval_route', ['approval_route_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('approval_status_entity_iin_fkey', 'approval_status', 'entity', ['entity_iin'], ['iin'], ondelete='CASCADE')
    op.create_foreign_key('approval_status_document_type_id_fkey', 'approval_status', 'document_type', ['document_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('approval_status_status_fkey', 'approval_status', 'route_status_type', ['status'], ['name'], ondelete='CASCADE')
    op.drop_constraint(None, 'approval_route', type_='foreignkey')
    op.drop_constraint(None, 'approval_route', type_='foreignkey')
    op.drop_constraint(None, 'approval_route', type_='foreignkey')
    op.drop_constraint(None, 'approval_route', type_='foreignkey')
    op.drop_constraint(None, 'approval_route', type_='foreignkey')
    op.drop_constraint(None, 'approval_route', type_='foreignkey')
    op.create_foreign_key('approval_route_approval_template_id_fkey', 'approval_route', 'approval_template', ['approval_template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('approval_route_entity_iin_fkey', 'approval_route', 'entity', ['entity_iin'], ['iin'], ondelete='CASCADE')
    op.create_foreign_key('approval_route_type_fkey', 'approval_route', 'step_type', ['type'], ['name'], ondelete='CASCADE')
    op.create_foreign_key('approval_route_approval_process_id_fkey', 'approval_route', 'approval_process', ['approval_process_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('approval_route_document_type_id_fkey', 'approval_route', 'document_type', ['document_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('approval_route_employee_id_fkey', 'approval_route', 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'approval_process', type_='foreignkey')
    op.drop_constraint(None, 'approval_process', type_='foreignkey')
    op.drop_constraint(None, 'approval_process', type_='foreignkey')
    op.drop_constraint(None, 'approval_process', type_='foreignkey')
    op.create_foreign_key('approval_process_status_fkey', 'approval_process', 'process_status_type', ['status'], ['name'], ondelete='CASCADE')
    op.create_foreign_key('approval_process_document_type_id_fkey', 'approval_process', 'document_type', ['document_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('approval_process_entity_iin_fkey', 'approval_process', 'entity', ['entity_iin'], ['iin'], ondelete='CASCADE')
    op.create_foreign_key('approval_process_approval_template_id_fkey', 'approval_process', 'approval_template', ['approval_template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
