"""3

Revision ID: 1edeaeff0402
Revises: 6ac90e4f7e15
Create Date: 2022-05-25 18:47:45.954920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edeaeff0402'
down_revision = '6ac90e4f7e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=False)
    op.create_foreign_key(None, 'users', 'employee', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###
