"""3

Revision ID: 2299af66330f
Revises: cafbb54663c1
Create Date: 2022-07-17 13:41:22.747268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2299af66330f'
down_revision = 'cafbb54663c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enum_business_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('full_name', sa.String(length=360), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enum_business_type_name'), 'enum_business_type', ['name'], unique=True)
    op.create_table('entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('full_name', sa.String(length=360), nullable=True),
    sa.Column('iin', sa.String(length=12), nullable=False),
    sa.Column('address', sa.String(length=350), nullable=True),
    sa.Column('comment', sa.String(length=350), nullable=True),
    sa.Column('director', sa.String(length=150), nullable=True),
    sa.Column('director_phone', sa.String(length=20), nullable=True),
    sa.Column('administrator', sa.String(length=150), nullable=True),
    sa.Column('administrator_phone', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('type_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['type_name'], ['enum_business_type.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_iin'), 'entity', ['iin'], unique=True)
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=350), nullable=True),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_foreign_key(None, 'approval_process', 'entity', ['entity_iin'], ['iin'])
    op.create_foreign_key(None, 'approval_route', 'entity', ['entity_iin'], ['iin'])
    op.create_foreign_key(None, 'approval_status', 'entity', ['entity_iin'], ['iin'])
    op.create_foreign_key(None, 'approval_template', 'entity', ['entity_iin'], ['iin'])
    op.create_foreign_key(None, 'counterparty', 'enum_business_type', ['type_name'], ['name'])
    op.create_foreign_key(None, 'employee_task', 'entity', ['entity_iin'], ['iin'])
    op.create_foreign_key(None, 'purchase_requisition', 'entity', ['entity_iin'], ['iin'])
    op.create_foreign_key(None, 'user', 'employee', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'user', 'entity', ['entity_iin'], ['iin'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'purchase_requisition', type_='foreignkey')
    op.drop_constraint(None, 'employee_task', type_='foreignkey')
    op.drop_constraint(None, 'counterparty', type_='foreignkey')
    op.drop_constraint(None, 'approval_template', type_='foreignkey')
    op.drop_constraint(None, 'approval_status', type_='foreignkey')
    op.drop_constraint(None, 'approval_route', type_='foreignkey')
    op.drop_constraint(None, 'approval_process', type_='foreignkey')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_entity_iin'), table_name='entity')
    op.drop_table('entity')
    op.drop_index(op.f('ix_enum_business_type_name'), table_name='enum_business_type')
    op.drop_table('enum_business_type')
    # ### end Alembic commands ###
