"""8

Revision ID: 28e54f24293d
Revises: 8a2fb1cad747
Create Date: 2022-05-01 15:19:51.124917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e54f24293d'
down_revision = '8a2fb1cad747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
