"""4

Revision ID: 2e0642028e6a
Revises: ef5a2dee5bdc
Create Date: 2022-04-03 17:49:22.111407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0642028e6a'
down_revision = 'ef5a2dee5bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_сounterparty_iin', table_name='сounterparty')
    op.drop_table('сounterparty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('сounterparty',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"сounterparty_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('iin', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=350), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=350), autoincrement=False, nullable=True),
    sa.Column('contact', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('endDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['business_type.id'], name='сounterparty_type_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='сounterparty_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='сounterparty_pkey')
    )
    op.create_index('ix_сounterparty_iin', 'сounterparty', ['iin'], unique=False)
    # ### end Alembic commands ###
