"""10

Revision ID: 389b23247900
Revises: 84eaea5f926c
Create Date: 2022-04-12 19:40:27.269612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389b23247900'
down_revision = '84eaea5f926c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
