"""9

Revision ID: 3ba2374d76c6
Revises: 28e54f24293d
Create Date: 2022-05-01 15:20:30.252911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba2374d76c6'
down_revision = '28e54f24293d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_requisition_items', sa.Column('hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_purchase_requisition_items_hash'), 'purchase_requisition_items', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_requisition_items_hash'), table_name='purchase_requisition_items')
    op.drop_column('purchase_requisition_items', 'hash')
    # ### end Alembic commands ###
