"""11

Revision ID: 40d0b624e33e
Revises: ffa88176b497
Create Date: 2022-04-12 22:15:35.501427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d0b624e33e'
down_revision = 'ffa88176b497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
