"""7

Revision ID: 4957728f9389
Revises: 65abf646afc3
Create Date: 2022-07-17 23:34:24.338731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4957728f9389'
down_revision = '65abf646afc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enum_task_status_type',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=360), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('task_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('enum_document_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.String(length=350), nullable=True),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ),
    sa.ForeignKeyConstraint(['enum_document_type_id'], ['enum_document_type.id'], ),
    sa.ForeignKeyConstraint(['status'], ['enum_task_status_type.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status_document_id'), 'task_status', ['document_id'], unique=False)
    op.create_index(op.f('ix_task_status_entity_iin'), 'task_status', ['entity_iin'], unique=False)
    op.create_index(op.f('ix_task_status_user_id'), 'task_status', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status_user_id'), table_name='task_status')
    op.drop_index(op.f('ix_task_status_entity_iin'), table_name='task_status')
    op.drop_index(op.f('ix_task_status_document_id'), table_name='task_status')
    op.drop_table('task_status')
    op.drop_table('enum_task_status_type')
    # ### end Alembic commands ###
