"""first7

Revision ID: 49a2494255d3
Revises: 7fff16b6e985
Create Date: 2022-04-05 22:33:39.338143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a2494255d3'
down_revision = '7fff16b6e985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('entity', sa.Column('end_date', sa.Date(), nullable=True))
    op.drop_column('entity', 'startDate')
    op.drop_column('entity', 'endDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('endDate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('entity', sa.Column('startDate', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('entity', 'end_date')
    op.drop_column('entity', 'start_date')
    # ### end Alembic commands ###
