"""20

Revision ID: 4a0fe2e7d558
Revises: ee43a878136a
Create Date: 2022-05-09 21:59:16.791145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0fe2e7d558'
down_revision = 'ee43a878136a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_requisition', sa.Column('guid', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_purchase_requisition_guid'), 'purchase_requisition', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_requisition_guid'), table_name='purchase_requisition')
    op.drop_column('purchase_requisition', 'guid')
    # ### end Alembic commands ###
