"""first18

Revision ID: 4e12a147b172
Revises: e163bf02fb66
Create Date: 2022-04-18 20:13:46.633354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e12a147b172'
down_revision = 'e163bf02fb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
