"""6

Revision ID: 4e53990e4937
Revises: 87ba6490dd96
Create Date: 2022-06-18 14:46:22.234264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e53990e4937'
down_revision = '87ba6490dd96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_employee_id', table_name='user')
    op.drop_index('ix_user_entity_iin', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_entity_iin', 'user', ['entity_iin'], unique=False)
    op.create_index('ix_user_employee_id', 'user', ['employee_id'], unique=False)
    # ### end Alembic commands ###
