"""9

Revision ID: 50540993203b
Revises: dec5e6a0e6e0
Create Date: 2022-03-28 17:27:12.199626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50540993203b'
down_revision = 'dec5e6a0e6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
