"""5

Revision ID: 58e0ca5a35f4
Revises: b77a02b01383
Create Date: 2022-07-17 22:18:41.162070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e0ca5a35f4'
down_revision = 'b77a02b01383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
