"""2

Revision ID: 5b7a7eae05f8
Revises: f718e05c2912
Create Date: 2022-04-21 21:11:40.929050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7a7eae05f8'
down_revision = 'f718e05c2912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_requisition', sa.Column('document_type_id', sa.Integer(), nullable = False))
    op.drop_constraint('purchase_requisition_document_type_name_fkey', 'purchase_requisition', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_requisition', 'document_type', ['document_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('purchase_requisition', 'document_type_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_requisition', sa.Column('document_type_name', sa.INTEGER(), autoincrement=False, nullable = False))
    op.drop_constraint(None, 'purchase_requisition', type_='foreignkey')
    op.create_foreign_key('purchase_requisition_document_type_name_fkey', 'purchase_requisition', 'document_type', ['document_type_name'], ['id'], ondelete='CASCADE')
    op.drop_column('purchase_requisition', 'document_type_id')
    # ### end Alembic commands ###
