"""12

Revision ID: 6477644a3691
Revises: 8ce1c8740088
Create Date: 2022-07-01 15:29:36.793752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6477644a3691'
down_revision = '8ce1c8740088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activity', sa.Column('action', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_activity', 'action')
    # ### end Alembic commands ###
