"""6

Revision ID: 65abf646afc3
Revises: 58e0ca5a35f4
Create Date: 2022-07-17 22:24:43.207508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65abf646afc3'
down_revision = '58e0ca5a35f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_task', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_task', 'content')
    # ### end Alembic commands ###
