"""11

Revision ID: 67e0cd2b7ed1
Revises: 68546be0cb5f
Create Date: 2022-03-29 16:52:48.112173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e0cd2b7ed1'
down_revision = '68546be0cb5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('entity_user_id_fkey', 'entity', type_='foreignkey')
    op.create_foreign_key(None, 'entity', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entity', type_='foreignkey')
    op.create_foreign_key('entity_user_id_fkey', 'entity', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
