"""10

Revision ID: 68546be0cb5f
Revises: 977173d5f5e4
Create Date: 2022-03-28 19:35:14.535297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68546be0cb5f'
down_revision = '977173d5f5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
