"""14

Revision ID: 6a5338a0abbf
Revises: 317cc2bbba4e
Create Date: 2022-05-03 22:46:46.685745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5338a0abbf'
down_revision = '317cc2bbba4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
