"""2

Revision ID: 6ac90e4f7e15
Revises: a284b713b60e
Create Date: 2022-05-23 22:25:26.171357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac90e4f7e15'
down_revision = 'a284b713b60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
