"""2

Revision ID: 700642bd4504
Revises: 615cb422f98e
Create Date: 2022-03-30 19:11:52.651153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700642bd4504'
down_revision = '615cb422f98e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'business_type', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business_type', type_='unique')
    # ### end Alembic commands ###
