"""19

Revision ID: 80144a312fc9
Revises: 97fc8d751ffa
Create Date: 2022-07-23 21:21:59.408753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80144a312fc9'
down_revision = '97fc8d751ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_requisition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.Column('counterparty_iin', sa.String(), nullable=False),
    sa.Column('enum_document_type_id', sa.Integer(), nullable=False),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['counterparty_iin'], ['counterparty.iin'], ),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ),
    sa.ForeignKeyConstraint(['enum_document_type_id'], ['enum_document_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requisition_author_id'), 'purchase_requisition', ['author_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisition_counterparty_iin'), 'purchase_requisition', ['counterparty_iin'], unique=False)
    op.create_index(op.f('ix_purchase_requisition_entity_iin'), 'purchase_requisition', ['entity_iin'], unique=False)
    op.create_index(op.f('ix_purchase_requisition_guid'), 'purchase_requisition', ['guid'], unique=False)
    op.create_table('purchase_requisition_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=360), nullable=False),
    sa.Column('description_code', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('purchase_requisition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_requisition_id'], ['purchase_requisition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requisition_items_hash'), 'purchase_requisition_items', ['hash'], unique=False)
    op.create_index(op.f('ix_purchase_requisition_items_purchase_requisition_id'), 'purchase_requisition_items', ['purchase_requisition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_requisition_items_purchase_requisition_id'), table_name='purchase_requisition_items')
    op.drop_index(op.f('ix_purchase_requisition_items_hash'), table_name='purchase_requisition_items')
    op.drop_table('purchase_requisition_items')
    op.drop_index(op.f('ix_purchase_requisition_guid'), table_name='purchase_requisition')
    op.drop_index(op.f('ix_purchase_requisition_entity_iin'), table_name='purchase_requisition')
    op.drop_index(op.f('ix_purchase_requisition_counterparty_iin'), table_name='purchase_requisition')
    op.drop_index(op.f('ix_purchase_requisition_author_id'), table_name='purchase_requisition')
    op.drop_table('purchase_requisition')
    # ### end Alembic commands ###
