"""21

Revision ID: 83571f6d2c66
Revises: ee43a878136a
Create Date: 2022-05-09 22:00:32.718426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83571f6d2c66'
down_revision = 'ee43a878136a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_requisition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=150), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.String(length=350), nullable=True),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.Column('counterparty_iin', sa.String(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_iin'], ['counterparty.iin'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requisition_counterparty_iin'), 'purchase_requisition', ['counterparty_iin'], unique=False)
    op.create_index(op.f('ix_purchase_requisition_entity_iin'), 'purchase_requisition', ['entity_iin'], unique=False)
    op.create_index(op.f('ix_purchase_requisition_guid'), 'purchase_requisition', ['guid'], unique=False)
    op.create_table('purchase_requisition_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=360), nullable=False),
    sa.Column('description_code', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('purchase_requisition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_requisition_id'], ['purchase_requisition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requisition_items_hash'), 'purchase_requisition_items', ['hash'], unique=False)
    op.create_index(op.f('ix_purchase_requisition_items_purchase_requisition_id'), 'purchase_requisition_items', ['purchase_requisition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_requisition_items_purchase_requisition_id'), table_name='purchase_requisition_items')
    op.drop_index(op.f('ix_purchase_requisition_items_hash'), table_name='purchase_requisition_items')
    op.drop_table('purchase_requisition_items')
    op.drop_index(op.f('ix_purchase_requisition_guid'), table_name='purchase_requisition')
    op.drop_index(op.f('ix_purchase_requisition_entity_iin'), table_name='purchase_requisition')
    op.drop_index(op.f('ix_purchase_requisition_counterparty_iin'), table_name='purchase_requisition')
    op.drop_table('purchase_requisition')
    # ### end Alembic commands ###
