"""11

Revision ID: 86ea26c1ca8b
Revises: bdaefa45540d
Create Date: 2022-05-02 21:11:23.498956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ea26c1ca8b'
down_revision = 'bdaefa45540d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_template',
    sa.Column('id', sa.Integer(), autoincrement = True, nullable = False),
    sa.Column('document_type_id', sa.String(), nullable = False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('entity_iin', sa.String(), nullable = False),
    sa.ForeignKeyConstraint(['document_type_id'], ['entity.iin'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_approval_template_entity_iin'), 'approval_template', ['entity_iin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_template_entity_iin'), table_name='approval_template')
    op.drop_table('approval_template')
    # ### end Alembic commands ###
