"""5

Revision ID: 87ba6490dd96
Revises: f1fc02837bd3
Create Date: 2022-06-18 14:15:12.854441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ba6490dd96'
down_revision = 'f1fc02837bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=350), nullable=True),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('entity_iin', sa.String(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_company', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_employee_id'), 'user', ['employee_id'], unique=False)
    op.create_index(op.f('ix_user_entity_iin'), 'user', ['entity_iin'], unique=False)
    op.create_foreign_key(None, 'approval_route', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'approval_status', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'approval_template_step', 'user', ['user_id'], ['id'])
    op.drop_column('entity', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'approval_template_step', type_='foreignkey')
    op.drop_constraint(None, 'approval_status', type_='foreignkey')
    op.drop_constraint(None, 'approval_route', type_='foreignkey')
    op.drop_index(op.f('ix_user_entity_iin'), table_name='user')
    op.drop_index(op.f('ix_user_employee_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
