"""7

Revision ID: 8a2fb1cad747
Revises: 0f713749d249
Create Date: 2022-05-01 15:16:53.113232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2fb1cad747'
down_revision = '0f713749d249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_requisition_items', sa.Column('hash', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_requisition_items_hash'), 'purchase_requisition_items', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_requisition_items_hash'), table_name='purchase_requisition_items')
    op.drop_column('purchase_requisition_items', 'hash')
    # ### end Alembic commands ###
