"""2-nd

Revision ID: 8bc52e0bad40
Revises: e2db1761bbab
Create Date: 2022-03-27 15:34:48.815027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8bc52e0bad40'
down_revision = 'e2db1761bbab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentType',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=350), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('entity',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('iin', sa.String(length=12), nullable=False),
    sa.Column('address', sa.String(length=350), nullable=True),
    sa.Column('comment', sa.String(length=350), nullable=True),
    sa.Column('director', sa.String(length=150), nullable=True),
    sa.Column('director_phone', sa.String(length=20), nullable=True),
    sa.Column('administrator', sa.String(length=150), nullable=True),
    sa.Column('administrator_phone', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('startDate', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('endDate', sa.String(length=20), nullable=True),
    sa.Column('user', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('iin')
    )
    op.drop_index('ix_microblog_posts_id', table_name='microblog_posts')
    op.drop_table('microblog_posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microblog_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=350), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='microblog_posts_pkey')
    )
    op.create_index('ix_microblog_posts_id', 'microblog_posts', ['id'], unique=False)
    op.drop_table('entity')
    op.drop_table('documentType')
    # ### end Alembic commands ###
