"""11

Revision ID: 8ce1c8740088
Revises: 7db0d6c829d1
Create Date: 2022-07-01 01:29:19.075561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce1c8740088'
down_revision = '7db0d6c829d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_activity_device_token_key', 'user_activity', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_activity_device_token_key', 'user_activity', ['device_token'])
    # ### end Alembic commands ###
