"""2

Revision ID: 910621cbb387
Revises: 
Create Date: 2022-05-10 17:31:19.738842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910621cbb387'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_process',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.Column('approval_template_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('signed', 'rejected', 'canceled', 'in_process', 'draft', name='status_type'), nullable=True),
    sa.ForeignKeyConstraint(['approval_template_id'], ['approval_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_process_approval_template_id'), 'approval_process', ['approval_template_id'], unique=False)
    op.create_index(op.f('ix_approval_process_document_id'), 'approval_process', ['document_id'], unique=False)
    op.create_index(op.f('ix_approval_process_entity_iin'), 'approval_process', ['entity_iin'], unique=False)
    op.create_index(op.f('ix_approval_process_status'), 'approval_process', ['status'], unique=False)
    op.create_table('approval_template_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('line', 'paralel', name='step_type'), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('approval_template_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approval_template_id'], ['approval_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_template_step_approval_template_id'), 'approval_template_step', ['approval_template_id'], unique=False)
    op.create_index(op.f('ix_approval_template_step_employee_id'), 'approval_template_step', ['employee_id'], unique=False)
    op.create_index(op.f('ix_approval_template_step_hash'), 'approval_template_step', ['hash'], unique=False)
    op.create_table('approval_route',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('line', 'paralel', name='step_type'), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('approval_template_id', sa.Integer(), nullable=False),
    sa.Column('approval_process_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approval_process_id'], ['approval_process.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approval_template_id'], ['approval_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ar_entity_document_id', 'approval_route', ['entity_iin', 'document_id'], unique=False)
    op.create_index(op.f('ix_approval_route_approval_process_id'), 'approval_route', ['approval_process_id'], unique=False)
    op.create_index(op.f('ix_approval_route_approval_template_id'), 'approval_route', ['approval_template_id'], unique=False)
    op.create_index(op.f('ix_approval_route_document_id'), 'approval_route', ['document_id'], unique=False)
    op.create_index(op.f('ix_approval_route_employee_id'), 'approval_route', ['employee_id'], unique=False)
    op.create_index(op.f('ix_approval_route_entity_iin'), 'approval_route', ['entity_iin'], unique=False)
    op.create_index('index_at_entity_document_type', 'approval_template', ['entity_iin', 'document_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_at_entity_document_type', table_name='approval_template')
    op.drop_index(op.f('ix_approval_route_entity_iin'), table_name='approval_route')
    op.drop_index(op.f('ix_approval_route_employee_id'), table_name='approval_route')
    op.drop_index(op.f('ix_approval_route_document_id'), table_name='approval_route')
    op.drop_index(op.f('ix_approval_route_approval_template_id'), table_name='approval_route')
    op.drop_index(op.f('ix_approval_route_approval_process_id'), table_name='approval_route')
    op.drop_index('idx_ar_entity_document_id', table_name='approval_route')
    op.drop_table('approval_route')
    op.drop_index(op.f('ix_approval_template_step_hash'), table_name='approval_template_step')
    op.drop_index(op.f('ix_approval_template_step_employee_id'), table_name='approval_template_step')
    op.drop_index(op.f('ix_approval_template_step_approval_template_id'), table_name='approval_template_step')
    op.drop_table('approval_template_step')
    op.drop_index(op.f('ix_approval_process_status'), table_name='approval_process')
    op.drop_index(op.f('ix_approval_process_entity_iin'), table_name='approval_process')
    op.drop_index(op.f('ix_approval_process_document_id'), table_name='approval_process')
    op.drop_index(op.f('ix_approval_process_approval_template_id'), table_name='approval_process')
    op.drop_table('approval_process')
    # ### end Alembic commands ###
