"""10

Revision ID: 977173d5f5e4
Revises: 50540993203b
Create Date: 2022-03-28 19:32:49.550811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977173d5f5e4'
down_revision = '50540993203b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
