"""18

Revision ID: 97fc8d751ffa
Revises: e24f9f03bd72
Create Date: 2022-07-23 19:48:46.791308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97fc8d751ffa'
down_revision = 'e24f9f03bd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('enum_document_type_id', sa.Integer(), nullable=False),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ),
    sa.ForeignKeyConstraint(['enum_document_type_id'], ['enum_document_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_task_author_id'), 'employee_task', ['author_id'], unique=False)
    op.create_index(op.f('ix_employee_task_entity_iin'), 'employee_task', ['entity_iin'], unique=False)
    op.create_index(op.f('ix_employee_task_guid'), 'employee_task', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_task_guid'), table_name='employee_task')
    op.drop_index(op.f('ix_employee_task_entity_iin'), table_name='employee_task')
    op.drop_index(op.f('ix_employee_task_author_id'), table_name='employee_task')
    op.drop_table('employee_task')
    # ### end Alembic commands ###
