"""16

Revision ID: 9b0552d819d3
Revises: 4143a487bc5d
Create Date: 2022-05-06 18:52:42.950071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0552d819d3'
down_revision = '4143a487bc5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
