"""1

Revision ID: a284b713b60e
Revises: 
Create Date: 2022-05-23 22:22:42.668382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a284b713b60e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_status_type',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=360), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('route_status_type',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=360), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('step_type',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=360), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('approval_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_at_entity_document_type', 'approval_template', ['entity_iin', 'document_type_id'], unique=False)
    op.create_index(op.f('ix_approval_template_entity_iin'), 'approval_template', ['entity_iin'], unique=False)
    op.create_table('approval_process',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('approval_template_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approval_template_id'], ['approval_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status'], ['process_status_type.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_process_approval_template_id'), 'approval_process', ['approval_template_id'], unique=False)
    op.create_index(op.f('ix_approval_process_document_id'), 'approval_process', ['document_id'], unique=False)
    op.create_index(op.f('ix_approval_process_entity_iin'), 'approval_process', ['entity_iin'], unique=False)
    op.create_table('approval_template_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('approval_template_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approval_template_id'], ['approval_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type'], ['step_type.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_template_step_approval_template_id'), 'approval_template_step', ['approval_template_id'], unique=False)
    op.create_index(op.f('ix_approval_template_step_employee_id'), 'approval_template_step', ['employee_id'], unique=False)
    op.create_index(op.f('ix_approval_template_step_hash'), 'approval_template_step', ['hash'], unique=False)
    op.create_table('approval_route',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('approval_template_id', sa.Integer(), nullable=False),
    sa.Column('approval_process_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approval_process_id'], ['approval_process.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approval_template_id'], ['approval_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type'], ['step_type.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ar_entity_document_id', 'approval_route', ['entity_iin', 'document_id'], unique=False)
    op.create_index(op.f('ix_approval_route_approval_process_id'), 'approval_route', ['approval_process_id'], unique=False)
    op.create_index(op.f('ix_approval_route_approval_template_id'), 'approval_route', ['approval_template_id'], unique=False)
    op.create_index(op.f('ix_approval_route_document_id'), 'approval_route', ['document_id'], unique=False)
    op.create_index(op.f('ix_approval_route_employee_id'), 'approval_route', ['employee_id'], unique=False)
    op.create_index(op.f('ix_approval_route_entity_iin'), 'approval_route', ['entity_iin'], unique=False)
    op.create_index(op.f('ix_approval_route_hash'), 'approval_route', ['hash'], unique=False)
    op.create_table('approval_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.String(length=350), nullable=True),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('approval_route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approval_route_id'], ['approval_route.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status'], ['route_status_type.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_as_approval_route_id_employee_id', 'approval_status', ['approval_route_id', 'employee_id'], unique=False)
    op.create_index(op.f('ix_approval_status_approval_route_id'), 'approval_status', ['approval_route_id'], unique=False)
    op.create_index(op.f('ix_approval_status_document_id'), 'approval_status', ['document_id'], unique=False)
    op.create_index(op.f('ix_approval_status_employee_id'), 'approval_status', ['employee_id'], unique=False)
    op.create_index(op.f('ix_approval_status_entity_iin'), 'approval_status', ['entity_iin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_status_entity_iin'), table_name='approval_status')
    op.drop_index(op.f('ix_approval_status_employee_id'), table_name='approval_status')
    op.drop_index(op.f('ix_approval_status_document_id'), table_name='approval_status')
    op.drop_index(op.f('ix_approval_status_approval_route_id'), table_name='approval_status')
    op.drop_index('idx_as_approval_route_id_employee_id', table_name='approval_status')
    op.drop_table('approval_status')
    op.drop_index(op.f('ix_approval_route_hash'), table_name='approval_route')
    op.drop_index(op.f('ix_approval_route_entity_iin'), table_name='approval_route')
    op.drop_index(op.f('ix_approval_route_employee_id'), table_name='approval_route')
    op.drop_index(op.f('ix_approval_route_document_id'), table_name='approval_route')
    op.drop_index(op.f('ix_approval_route_approval_template_id'), table_name='approval_route')
    op.drop_index(op.f('ix_approval_route_approval_process_id'), table_name='approval_route')
    op.drop_index('idx_ar_entity_document_id', table_name='approval_route')
    op.drop_table('approval_route')
    op.drop_index(op.f('ix_approval_template_step_hash'), table_name='approval_template_step')
    op.drop_index(op.f('ix_approval_template_step_employee_id'), table_name='approval_template_step')
    op.drop_index(op.f('ix_approval_template_step_approval_template_id'), table_name='approval_template_step')
    op.drop_table('approval_template_step')
    op.drop_index(op.f('ix_approval_process_entity_iin'), table_name='approval_process')
    op.drop_index(op.f('ix_approval_process_document_id'), table_name='approval_process')
    op.drop_index(op.f('ix_approval_process_approval_template_id'), table_name='approval_process')
    op.drop_table('approval_process')
    op.drop_index(op.f('ix_approval_template_entity_iin'), table_name='approval_template')
    op.drop_index('index_at_entity_document_type', table_name='approval_template')
    op.drop_table('approval_template')
    op.drop_table('step_type')
    op.drop_table('route_status_type')
    op.drop_table('process_status_type')
    # ### end Alembic commands ###
