"""15

Revision ID: bbda53040c04
Revises: 07bc969d4f57
Create Date: 2022-07-23 15:01:53.860460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbda53040c04'
down_revision = '07bc969d4f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
