"""2

Revision ID: bc6274ab7a11
Revises: 910621cbb387
Create Date: 2022-05-10 18:48:02.401438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6274ab7a11'
down_revision = '910621cbb387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_process', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('approval_process', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_process', 'end_date')
    op.drop_column('approval_process', 'start_date')
    # ### end Alembic commands ###
