"""10

Revision ID: bdaefa45540d
Revises: 3ba2374d76c6
Create Date: 2022-05-02 21:10:10.275045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdaefa45540d'
down_revision = '3ba2374d76c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
