"""14

Revision ID: c1a642aa0290
Revises: e18753a26d51
Create Date: 2022-04-13 23:13:12.399956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a642aa0290'
down_revision = 'e18753a26d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
