"""2

Revision ID: cafbb54663c1
Revises: 982958983d81
Create Date: 2022-07-16 18:36:47.524004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafbb54663c1'
down_revision = '982958983d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('entity_iin', sa.String(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_company', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_foreign_key(None, 'approval_route', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'approval_status', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'approval_template_step', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'employee_task', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'purchase_requisition', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'user_activity', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_activity', type_='foreignkey')
    op.drop_constraint(None, 'purchase_requisition', type_='foreignkey')
    op.drop_constraint(None, 'employee_task', type_='foreignkey')
    op.drop_constraint(None, 'approval_template_step', type_='foreignkey')
    op.drop_constraint(None, 'approval_status', type_='foreignkey')
    op.drop_constraint(None, 'approval_route', type_='foreignkey')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
