"""13

Revision ID: cc46830a466d
Revises: bc6274ab7a11
Create Date: 2022-05-19 22:02:51.858072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc46830a466d'
down_revision = 'bc6274ab7a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_route', sa.Column('hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_approval_route_hash'), 'approval_route', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_route_hash'), table_name='approval_route')
    op.drop_column('approval_route', 'hash')
    # ### end Alembic commands ###
