"""15

Revision ID: d10c2e4fb98c
Revises: 312863b4f0ae
Create Date: 2022-04-14 12:03:35.830963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10c2e4fb98c'
down_revision = '312863b4f0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
