"""8

Revision ID: dec5e6a0e6e0
Revises: 0405816db021
Create Date: 2022-03-28 16:55:53.375942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec5e6a0e6e0'
down_revision = '0405816db021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_entity_user_id'), 'entity', ['user_id'], unique=False)
    op.create_foreign_key(None, 'entity', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entity', type_='foreignkey')
    op.drop_index(op.f('ix_entity_user_id'), table_name='entity')
    op.drop_column('entity', 'user_id')
    # ### end Alembic commands ###
