"""8

Revision ID: dff796cba149
Revises: 4957728f9389
Create Date: 2022-07-19 14:04:24.658589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff796cba149'
down_revision = '4957728f9389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_status', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_status_assigned_user_id'), 'task_status', ['assigned_user_id'], unique=False)
    op.create_foreign_key(None, 'task_status', 'user', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_status', type_='foreignkey')
    op.drop_index(op.f('ix_task_status_assigned_user_id'), table_name='task_status')
    op.drop_column('task_status', 'assigned_user_id')
    # ### end Alembic commands ###
