"""17

Revision ID: e163bf02fb66
Revises: 719dd3d5523d
Create Date: 2022-04-14 20:32:41.043951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e163bf02fb66'
down_revision = '719dd3d5523d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
