"""13

Revision ID: e18753a26d51
Revises: 40d0b624e33e
Create Date: 2022-04-13 20:08:02.401751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e18753a26d51'
down_revision = '40d0b624e33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_purchase_requisition_guid', table_name='purchase_requisition')
    op.drop_table('purchase_requisition')
    op.drop_constraint('counterparty_type_id_fkey', 'counterparty', type_='foreignkey')
    op.drop_constraint('counterparty_user_id_fkey', 'counterparty', type_='foreignkey')
    op.create_foreign_key(None, 'counterparty', 'business_type', ['type_id'], ['id'])
    op.drop_column('counterparty', 'end_date')
    op.drop_column('counterparty', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counterparty', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('counterparty', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'counterparty', type_='foreignkey')
    op.create_foreign_key('counterparty_user_id_fkey', 'counterparty', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('counterparty_type_id_fkey', 'counterparty', 'business_type', ['type_id'], ['id'], ondelete='CASCADE')
    op.create_table('purchase_requisition',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=350), autoincrement=False, nullable=True),
    sa.Column('sum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('counterparty_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], name='purchase_requisition_counterparty_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], name='purchase_requisition_document_type_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name='purchase_requisition_entity_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='purchase_requisition_pkey')
    )
    op.create_index('ix_purchase_requisition_guid', 'purchase_requisition', ['guid'], unique=False)
    # ### end Alembic commands ###
