"""17

Revision ID: e24f9f03bd72
Revises: 9430890fe500
Create Date: 2022-07-23 19:36:13.462186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24f9f03bd72'
down_revision = '9430890fe500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
