"""5

Revision ID: e253ae44dc21
Revises: d03a314c5794
Create Date: 2022-04-03 18:04:03.411735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e253ae44dc21'
down_revision = 'd03a314c5794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('is_company', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_company')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
