"""autoincriment

Revision ID: e2db1761bbab
Revises: 57e50d3e12c8
Create Date: 2022-03-26 19:49:09.857476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2db1761bbab'
down_revision = '57e50d3e12c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
