"""four

Revision ID: e4c0b34feb37
Revises: 13dae53594ee
Create Date: 2022-03-28 14:35:25.026224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c0b34feb37'
down_revision = '13dae53594ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
