"""4

Revision ID: f1fc02837bd3
Revises: 151013ade2b3
Create Date: 2022-06-18 12:52:39.001058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fc02837bd3'
down_revision = '151013ade2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_company', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.add_column('approval_route', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_approval_route_employee_id', table_name='approval_route')
    op.create_index(op.f('ix_approval_route_user_id'), 'approval_route', ['user_id'], unique=False)
    op.drop_constraint('approval_route_employee_id_fkey', 'approval_route', type_='foreignkey')
    op.create_foreign_key(None, 'approval_route', 'user', ['user_id'], ['id'])
    op.drop_column('approval_route', 'employee_id')
    op.add_column('approval_status', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('idx_as_approval_route_id_employee_id', table_name='approval_status')
    op.drop_index('ix_approval_status_employee_id', table_name='approval_status')
    op.create_index('idx_as_approval_route_id_user_id', 'approval_status', ['approval_route_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_approval_status_user_id'), 'approval_status', ['user_id'], unique=False)
    op.drop_constraint('approval_status_employee_id_fkey', 'approval_status', type_='foreignkey')
    op.create_foreign_key(None, 'approval_status', 'user', ['user_id'], ['id'])
    op.drop_column('approval_status', 'employee_id')
    op.add_column('approval_template_step', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_approval_template_step_employee_id', table_name='approval_template_step')
    op.create_index(op.f('ix_approval_template_step_user_id'), 'approval_template_step', ['user_id'], unique=False)
    op.drop_constraint('approval_template_step_employee_id_fkey', 'approval_template_step', type_='foreignkey')
    op.create_foreign_key(None, 'approval_template_step', 'user', ['user_id'], ['id'])
    op.drop_column('approval_template_step', 'employee_id')
    op.create_foreign_key(None, 'employee', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'entity', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entity', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.add_column('approval_template_step', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'approval_template_step', type_='foreignkey')
    op.create_foreign_key('approval_template_step_employee_id_fkey', 'approval_template_step', 'employee', ['employee_id'], ['id'])
    op.drop_index(op.f('ix_approval_template_step_user_id'), table_name='approval_template_step')
    op.create_index('ix_approval_template_step_employee_id', 'approval_template_step', ['employee_id'], unique=False)
    op.drop_column('approval_template_step', 'user_id')
    op.add_column('approval_status', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'approval_status', type_='foreignkey')
    op.create_foreign_key('approval_status_employee_id_fkey', 'approval_status', 'employee', ['employee_id'], ['id'])
    op.drop_index(op.f('ix_approval_status_user_id'), table_name='approval_status')
    op.drop_index('idx_as_approval_route_id_user_id', table_name='approval_status')
    op.create_index('ix_approval_status_employee_id', 'approval_status', ['employee_id'], unique=False)
    op.create_index('idx_as_approval_route_id_employee_id', 'approval_status', ['approval_route_id', 'employee_id'], unique=False)
    op.drop_column('approval_status', 'user_id')
    op.add_column('approval_route', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'approval_route', type_='foreignkey')
    op.create_foreign_key('approval_route_employee_id_fkey', 'approval_route', 'employee', ['employee_id'], ['id'])
    op.drop_index(op.f('ix_approval_route_user_id'), table_name='approval_route')
    op.create_index('ix_approval_route_employee_id', 'approval_route', ['employee_id'], unique=False)
    op.drop_column('approval_route', 'user_id')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
