"""1

Revision ID: f718e05c2912
Revises: 
Create Date: 2022-04-21 19:37:44.783107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f718e05c2912'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('full_name', sa.String(length=360), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_type_name'), 'business_type', ['name'], unique=True)
    op.create_table('document_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=350), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_company', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('counterparty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('full_name', sa.String(length=360), nullable=True),
    sa.Column('iin', sa.String(length=12), nullable=False),
    sa.Column('address', sa.String(length=350), nullable=True),
    sa.Column('comment', sa.String(length=350), nullable=True),
    sa.Column('contact', sa.String(length=150), nullable=True),
    sa.Column('type_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['type_name'], ['business_type.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparty_iin'), 'counterparty', ['iin'], unique=True)
    op.create_table('entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('full_name', sa.String(length=360), nullable=True),
    sa.Column('iin', sa.String(length=12), nullable=False),
    sa.Column('address', sa.String(length=350), nullable=True),
    sa.Column('comment', sa.String(length=350), nullable=True),
    sa.Column('director', sa.String(length=150), nullable=True),
    sa.Column('director_phone', sa.String(length=20), nullable=True),
    sa.Column('administrator', sa.String(length=150), nullable=True),
    sa.Column('administrator_phone', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('type_name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_name'], ['business_type.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_iin'), 'entity', ['iin'], unique=True)
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=350), nullable=True),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('purchase_requisition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=150), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.String(length=350), nullable=True),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.Column('counterparty_iin', sa.String(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('entity_iin', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_iin'], ['counterparty.iin'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_iin'], ['entity.iin'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requisition_counterparty_iin'), 'purchase_requisition', ['counterparty_iin'], unique=False)
    op.create_index(op.f('ix_purchase_requisition_entity_iin'), 'purchase_requisition', ['entity_iin'], unique=False)
    op.create_index(op.f('ix_purchase_requisition_guid'), 'purchase_requisition', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_requisition_guid'), table_name='purchase_requisition')
    op.drop_index(op.f('ix_purchase_requisition_entity_iin'), table_name='purchase_requisition')
    op.drop_index(op.f('ix_purchase_requisition_counterparty_iin'), table_name='purchase_requisition')
    op.drop_table('purchase_requisition')
    op.drop_table('employee')
    op.drop_index(op.f('ix_entity_iin'), table_name='entity')
    op.drop_table('entity')
    op.drop_index(op.f('ix_counterparty_iin'), table_name='counterparty')
    op.drop_table('counterparty')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('notes')
    op.drop_table('document_type')
    op.drop_index(op.f('ix_business_type_name'), table_name='business_type')
    op.drop_table('business_type')
    # ### end Alembic commands ###
